name: Build and Push Prod Container

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
      - name: Log into ghcr
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push the container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/nicharcha82/leo-bot-latest:latest
            
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.HOST_SSH_KEY }}
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          script: |
            docker pull ghcr.io/nicharcha82/leo-bot-latest:latest
            docker rm -f leo-bot
            docker run --env-file /root/leo-bot/.env -d \
            -p 443:5000 \
            -v /root/leo-bot/certs:/app/certificates \
            -v /root/leo-bot/logs:/app/logging/logs \
            --name leo-bot \
            --restart unless-stopped \
            ghcr.io/nicharcha82/leo-bot-latest:latest