name: Build and Push Stage Container

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
      - name: Log into ghcr
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push the container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/nicharcha82/leo-bot-beta:beta
    